# Site settings
title: Reyhoun
title_fa: ریحون
email: info@reyhoun.com
description: > # this means to ignore newlines until "baseurl:"
  Creative focus on simplicity and things that appear on screens
description_fa: >
  تمرکز خلاقانه برای ساده سازی چیزهایی که بر روی صفحه های نمایش نشان داده می شود
baseurl: "" # the subpath of your site, e.g. /blog/
baseurl_fa: "/fa"
url: "http://reyhoun.com" # the base hostname & protocol for your site
twitter_username: ReyhounDesign
github_username:  reyhoun
behance_username:  reyhoun

# Build settings
markdown: kramdown
highlighter: rouge
encoding: utf-8
permalink: /:categories/:title
exclude: ["node_modules", "assets/scss", "assets/vendor", "gulpfile.js", "package.json", "bower.json", "LICENSE", "Gemfile", "Gemfile.lock"]

# Menu Data
navigation:
- text: Portfolio
  url: /
- text: About
  url: /about/
- text: Blog
  url: /blog/
- text: Hire Us
  url: /contact/

# Menu Data - Farsi
navigation_fa:
- text: خدمات ما
  url: /fa/
- text: درباره ما
  url: /fa/about/
- text: وبلاگ
  url: /fa/blog/
- text: تماس با ما
  url: /fa/contact/